server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
     config:
       server:
         git:
           username: peilewang
           password: wsxp15531667795@
           uri: https://github.com/peilewang/SpringCloud
           # 配置git仓库的地址
           search-paths: config-repo
           # git仓库地址下的相对地址，可以配置多个，⽤,分割。