server:
  port: 3333
spring:
  application:
    name: microservice-zipkin-user
  zipkin:
    base-url: http://localhost:2222
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
