server:
  port: 8000
eureka:
   instance:
     prefer-ip-address: true
   client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microserice-eureka-user
  datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&setUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 12345678
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          initial-size: 1
          min-idle: 3
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 30000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          filters: stat,wall,slf4j
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #热部署配置
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
       enabled: true #是否支持热部署
swagger:
  #配置Swagger扫包范围
  base-package: com.itheima.springcloud.controller
  # 需要处理的基础URL规则，默认：/**
  base-path: /*
logging:
  level:
    com.itheima.springcloud.mapper: debug
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
        map-underscore-to-camel-case: true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

