server:
  port: 8000
eureka:
   instance:
     prefer-ip-address: true
   client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microserice-eureka-user
  datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&setUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 12345678
        driver-class-name: com.mysql.jdbc.Driver
swagger:
  #配置Swagger扫包范围
  base-package: com.itheima.springcloud.controller
  # 需要处理的基础URL规则，默认：/**
  base-path: /*
logging:
  level:
    com.itheima.springcloud.mapper: debug
mybatis:
  mapper-locations: classpath*:mapper/*.xml