server:
  port: 4444
spring:
  application:
    name: microservice-zipkin-user02
  zipkin:
    base-url: http://localhost:2222
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
　　　　